package xionglongztz;

public class DsPapiVariableList {
    public static String PAPI_VARIABLE_LIST = """
%player_allow_flight%
%player_armor_helmet_name%
%player_armor_helmet_data%
%player_armor_helmet_durability%
%player_armor_chestplate_name%
%player_armor_chestplate_data%
%player_armor_chestplate_durability%
%player_armor_leggings_name%
%player_armor_leggings_data%
%player_armor_leggings_durability%
%player_armor_boots_name%
%player_armor_boots_data%
%player_armor_boots_durability%
%player_bed_x%
%player_bed_y%
%player_bed_z%
%player_bed_world%
%player_biome%
%player_biome_capitalized%
%player_block_underneath%
%player_can_pickup_items%
%player_colored_ping%
%player_compass_world%
%player_compass_x%
%player_compass_y%
%player_compass_z%
%player_custom_name%
%player_current_exp%
%player_direction%
%player_direction_xz%
%player_displayname%
%player_list_name%
%player_exp%
%player_exp_to_level%
%player_first_join_date%
%player_first_played%
%player_first_join%
%player_first_played_formatted%
%player_fly_speed%
%player_food_level%
%player_gamemode%
%player_has_empty_slot%
%player_has_played_before%
%player_empty_slots%
%player_has_potioneffect_<effect>%
%player_has_permission_<permission>%
%player_health%
%player_health_rounded%
%player_health_scale%
%player_ip%
%player_online%
%player_is_whitelisted%
%player_is_banned%
%player_is_flying%
%player_is_sneaking%
%player_is_sprinting%
%player_is_sleeping%
%player_is_inside_vehicle%
%player_is_op%
%player_item_in_hand%
%player_item_in_hand_name%
%player_item_in_hand_data%
%player_item_in_hand_durability%
%player_item_in_hand_level_<enchantment>%
%player_item_in_offhand%
%player_item_in_offhand_name%
%player_item_in_offhand_data%
%player_item_in_offhand_durability%
%player_item_in_offhand_level_<enchantment>%
%player_locale%
%player_locale_display_name%
%player_locale_short%
%player_locale_country%
%player_locale_display_country%
%player_last_damage%
%player_last_played%
%player_last_join%
%player_last_played_formatted%
%player_last_join_date%
%player_level%
%player_light_level%
%player_max_air%
%player_max_health%
%player_max_health_rounded%
%player_max_no_damage_ticks%
%player_minutes_lived%
%player_name%
%player_no_damage_ticks%
%player_ping%
%player_ping_<playername>%
%player_remaining_air%
%player_saturation%
%player_seconds_lived%
%player_sleep_ticks%
%player_thunder_duration%
%player_ticks_lived%
%player_time%
%player_time_offset%
%player_total_exp%
%player_uuid%
%player_walk_speed%
%player_weather_duration%
%player_world%
%player_world_type%
%player_world_time_12%
%player_world_time_24%
%player_x%
%player_x_long%
%player_y%
%player_y_long%
%player_z%
%player_z_long%
%player_yaw%
%player_pitch%
%player_absorption%

%vault_eco_balance%
%vault_eco_balance_<number>dp%
%vault_eco_balance_fixed%
%vault_eco_balance_formatted%
%vault_eco_balance_commas%
%vault_group%
%vault_group_capital%
%vault_groups%
%vault_groups_capital%
%vault_prefix%
%vault_suffix%
%vault_groupprefix%
%vault_groupprefix_#%
%vault_groupsuffix%
%vault_groupsuffix_#%
%vault_hasgroup_<group>%
%vault_inprimarygroup_<group>%

%server_name%
%server_online%
%server_version%
%server_version_full%
%server_variant%
%server_build%
%server_max_players%
%server_online_(world)%
%server_ram_free%
%server_ram_max%
%server_ram_total%
%server_ram_used%
%server_unique_joins%
%server_uptime%
%server_time_<SimpleDateFormat>%
%server_countdown_<SimpleDateFormat>_<ActualDateAndTimeBasedOnSDFSpecified>%
%server_countdown_raw_<SimpleDateFormat>_<ActualDateAndTimeBasedOnSDFSpecified>%
%server_countup_<SimpleDateFormat>_<ActualDateAndTimeBasedOnSDFSpecified>%
%server_countup_raw_<SimpleDateFormat>_<ActualDateAndTimeBasedOnSDFSpecified>%
%server_tps%
%server_tps_1%
%server_tps_5%
%server_tps_15%
%server_tps_1_colored%
%server_tps_5_colored%
%server_tps_15_colored%
%server_has_whitelist%
%server_total_chunks%
%server_total_living_entities%
%server_total_entities%

%statistic_<StatisticTypeInSpigotAPI>%
%statistic_animals_bred%
%statistic_armor_cleaned%
%statistic_aviate_one_cm%
%statistic_banner_cleaned%
%statistic_beacon_interacted%
%statistic_boat_one_cm%
%statistic_break_item%
%statistic_break_item:<material>,<material2>%
%statistic_brewingstand_interaction%
%statistic_cake_slices_eaten%
%statistic_cauldron_filled%
%statistic_cauldron_used%
%statistic_chest_opened%
%statistic_climb_one_cm%
%statistic_crafting_table_interaction%
%statistic_craft_item%
%statistic_craft_item:<material>,<material2>%
%statistic_crouch_one_cm%
%statistic_damage_dealt%
%statistic_damage_taken%
%statistic_days_played%
%statistic_days_played_remaining%
%statistic_days_since_death%
%statistic_deaths%
%statistic_dispenser_inspected%
%statistic_dive_one_cm%
%statistic_drop%
%statistic_dropper_inspected%
%statistic_enderchest_opened%
%statistic_entity_killed_by:<mob>,<mob2>%
%statistic_fall_one_cm%
%statistic_fish_caught%
%statistic_flower_potted%
%statistic_fly_one_cm%
%statistic_furnace_interaction%
%statistic_hopper_inspected%
%statistic_horse_one_cm%
%statistic_hours_played%
%statistic_hours_played_remaining%
%statistic_hours_since_death%
%statistic_item_enchanted%
%statistic_join_game%
%statistic_jump%
%statistic_junk_fished%
%statistic_kill_entity:<mob>,<mob2>%
%statistic_leave_game%
%statistic_minecart_one_cm%
%statistic_mine_block%
%statistic_mine_block:<material>,<material2>%
%statistic_minutes_played%
%statistic_minutes_played_remaining%
%statistic_minutes_since_death%
%statistic_noteblock_played%
%statistic_noteblock_tuned%
%statistic_pig_one_cm%
%statistic_player_kills%
%statistic_record_played%
%statistic_seconds_played%
%statistic_seconds_played_remaining%
%statistic_seconds_since_death%
%statistic_sleep_in_bed%
%statistic_sneak_time%
%statistic_sprint_one_cm%
%statistic_swim_one_cm%
%statistic_talked_to_villager%
%statistic_ticks_played%
%statistic_ticks_since_death%
%statistic_time_played%
%statistic_time_since_death%
%statistic_traded_with_villager%
%statistic_trapped_chest_triggered%
%statistic_treasure_fished%
%statistic_use_item%
%statistic_use_item:<material>,<material2>%
%statistic_walk_one_cm%

%math_<expression>%
%math_[decimals]:[rounding]_<expression>%
            """;;
}
